#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2026 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

updater.nvdcve.enabled=false
analyzer.nvdcve.enabled=false
updater.versioncheck.enabled=false
hosted.suppressions.enabled=false
