# Copyright (c) 2026 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Disable NVD CVE download and analysis only.
# CPE Analyzer and KEV Analyzer remain active.
updater.nvdcve.enabled=false
analyzer.nvdcve.enabled=false
updater.versioncheck.enabled=false
hosted.suppressions.enabled=false
