# Running tests with tox for releasing new version

name: Pull requests fosslight_binary_scanner

on:
  pull_request:
    branches:
      - '*'
jobs:
  check-commit-message:
    uses: fosslight/.github/.github/workflows/base-check-commit-message.yml@main
    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}

  run_tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: |
        tox -e release

  exe_windows:
    name: Run an executable for windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install & Run
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller
        pyinstaller --onefile cli.py -n cli --additional-hooks-dir=hooks --hidden-import=pkg_resources.extern &&
        move dist\cli.exe tests\fosslight_bin_windows.exe
        .\tests\fosslight_bin_windows.exe
  
  reuse:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
